spring:
  data:
    mongodb:
      uri: mongodb+srv://${ID}:${KEY}@testdb.b78i0zh.mongodb.net/?retryWrites=true&w=majority
      database: testDB
  thymeleaf3:
    decoupled-logic: true
  data.rest:
    base-path: /api
    detection-strategy: annotated
Java:
  runtime:
    version: 1.8
