spring:
  data:
    mongodb:
      uri: env("DATABASE_URL")
      database: testDB
  thymeleaf3:
    decoupled-logic: true
  data.rest:
    base-path: /api
    detection-strategy: annotated
Java:
  runtime:
    version: 17
